### ISSUE TITLE
Can't serve static files from /static folder

### ISSUE THREAD

**Issue by ferdinandfrank** [wan2land/serverless-nuxt#53] opened 2020-03-09 16:49 UTC
It seems like files (images, robots.txt, ...) can't be served from the Lambda and the API gateway that is located in the Nuxt project's `/static` folder.
E.g., I do have a valid `robots.txt` file located in `/static/robots.txt` that can be served locally using `npm run dev`:
![image](https://user-images.githubusercontent.com/19409640/76237151-10e9d900-622e-11ea-81ad-eb245a946ace.png)

But in production only a random string is being send:
![image](https://user-images.githubusercontent.com/19409640/76237048-e8fa7580-622d-11ea-979e-d5bd976a68c9.png)

The same applies for any image located in the `/static` folder.
Can someone reproduce the issue or did I miss a step in the setup?

**Comment by wan2land** [comment] 2020-03-11 06:28
The txt file also seems to be transferred to base64. I'll test it and talk again. :-)

**Comment by wan2land** [comment] 2020-03-15 16:36
The bug could not be reproduced.

Please provide the API Gateway settings(AWS > API Gateway > Settings > Binary Media Type) and serverless.yml. 🙏

**Comment by ferdinandfrank** [comment] 2020-03-15 21:47
@wan2land Thanks for your time! The weird thing is that it now works on my DEV environment but not on my PROD environment. Since it's exactly the same code the issue can't be caused by the package, so sorry for that!
My guess is a weird caching issue on CloudFront and the API Gateway, I wasn't able to solve yet. The only purpose of the CloudFront distribution in front of the API Gateway is to redirect `http` to `https`.
I already invalidated the cache there, but that didn't fix it either.
I can't really tell the reason for that by the response headers either:
![image](https://user-images.githubusercontent.com/19409640/76711237-75b1a180-670e-11ea-8988-e09a92edd29e.png)

The page with the `robots.txt` is the following: https://spoferan.com/robots.txt.
But since the issue isn't caused by this plugin, feel free to close the issue. ;)

**Closed** 2020-04-23 07:13 UTC
Labels: bug
